---

- include: ubuntu-14.04.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Install MariaDB
  sudo: yes
  apt: name="{{ item }}" state=present
  with_items:
    - mariadb-server
    - mariadb-client
